apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-advisor-deployment
  namespace: packapp04
spec:
  selector:
    matchLabels:
      app: back-advisor
  replicas: 1
  template:
    metadata:
      labels:
        app: back-advisor
    spec:
      containers:
      - name: back-advisor
        image: registry.hackathon-container.com/packapp04/back-advisor:2.0
        ports:
        - containerPort: 9090
      imagePullSecrets:
      - name: registry
---
apiVersion: v1
kind: Service
metadata:
  name: back-advisor-svc
  namespace: packapp04
spec:
  type: ClusterIP
  selector:
    app: back-advisor
  ports:
  - name: back-advisor-ports 
    port: 9090
    targetPort: 9090
    protocol: TCP
